### ISSUE TITLE
how to fixed ?

### ISSUE THREAD

**Issue by successed** [SkriptLang/Skript#1853]
[07:13:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: ch.njol.util.NonNullPair.getSecond()Ljava/lang/Object;
        at ch.njol.skript.command.Commands.loadCommand(Commands.java:379) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:462) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193) ~[?:?]
        at ch.njol.skript.Skript.reload(Skript.java:548) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        ... 15 more

**Comment by successed** [comment]
[07:16:16 WARN]: [Skript] Task #88 for Skript v2.1.2 generated an exception
java.lang.NoSuchMethodError: ch.njol.util.NonNullPair.getSecond()Ljava/lang/Object;
        at ch.njol.skript.command.Commands.loadCommand(Commands.java:379) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:462) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:378) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by TheBentoBox** [comment]
You're using an incredibly old version of Skript. [This version](https://skripttools.net/dl/Skript+2.2-Fixes-V8b.jar) will probably work better for you on 1.8. Our latest releases can be found [here](https://github.com/SkriptLang/Skript/releases), but be warned that Skript no longer officially supports 1.8 so releases from that second page are unlikely to work with 1.8.

**Comment by successed** [comment]
> You're using an incredibly old version of Skript. [This version](https://skripttools.net/dl/Skript+2.2-Fixes-V8b.jar) will probably work better for you on 1.8. Our latest releases can be found [here](https://github.com/SkriptLang/Skript/releases), but be warned that Skript no longer officially supports 1.8 so releases from that second page are unlikely to work with 1.8.

org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: ch.njol.util.NonNullPair.getSecond()Ljava/lang/Object;
        at ch.njol.skript.command.Commands.loadCommand(Commands.java:379) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:462) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193) ~[?:?]
        at ch.njol.skript.Skript.reload(Skript.java:548) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        ... 15 more

**Comment by successed** [comment]
> You're using an incredibly old version of Skript. [This version](https://skripttools.net/dl/Skript+2.2-Fixes-V8b.jar) will probably work better for you on 1.8. Our latest releases can be found [here](https://github.com/SkriptLang/Skript/releases), but be warned that Skript no longer officially supports 1.8 so releases from that second page are unlikely to work with 1.8.

http://prntscr.com/md2lnn

**Comment by TheBentoBox** [comment]
You're still using an old version of Skript in that error. Not sure what you're wanting but this isn't the place to ask for help like this. [Use the forums](https://forums.skunity.com/).
